export const ACTION_TYPES = {
  GET_LIST_TALLERES_START: "GET_LIST_TALLERES_START",
  GET_LIST_TALLERES_FINISH: "GET_LIST_TALLERES_FINISH",
  GET_LIST_TALLERES_FAILED: "GET_LIST_TALLERES_FAILED",

  GET_LIST_RINCONES_START: "GET_LIST_RINCONES_START",
  GET_LIST_RINCONES_FINISH: "GET_LIST_RINCONES_FINISH",
  GET_LIST_RINCONES_FAILED: "GET_LIST_RINCONES_FAILED",

  GET_RESOURCE_START: "GET_RESOURCE_START",
  GET_RESOURCE_FAILED: "GET_RESOURCE_FAILED",
  GET_RESOURCE_FINISH: "GET_RESOURCE_FINISH",
};
